version: "2.0"
services:
  broker:
    image: rabbitmq
    hostname: rabbitmq
    container_name: "rabbitmq"
  worker:
    build: worker
    container_name: "worker"
    volumes:
      - ./worker:/app
    depends_on:
      - broker
    links:
      - broker
    command: ["/bin/sh", "-c", "celery -A tasks worker --loglevel=info"]

  web:
    build: server
    container_name: "server"
    hostname: web
    working_dir: "/app"
    command: ["/bin/sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - broker
      - worker
    links:
      - broker