# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0002_auto_20170723_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilteredResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(choices=[('edge', 'Edge'), ('red_tint', 'Red Tint'), ('swirl', 'Swirl')], max_length=10, verbose_name='Filter')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtered_image', to='images.Image', verbose_name='Input image')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_type', to='images.Image', verbose_name='Result image')),
            ],
        ),
    ]
