# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredresource',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter_type', to='images.Image', verbose_name='Result image'),
        ),
    ]
