# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0002_auto_20170723_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredresource',
            name='status',
            field=models.CharField(default='in_progress', max_length=15, verbose_name='Status'),
        ),
    ]
