# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filters', '0003_filteredresource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filteredresource',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done')], default='in_progress', max_length=15, verbose_name='Status'),
        ),
    ]
