# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images', verbose_name='Image')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
    ]
