# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='base64_file',
            field=models.FileField(blank=True, null=True, upload_to='base64_files/%Y/%m/%d', verbose_name='Base64 file'),
        ),
    ]
